
```{r cache=TRUE}
library(knitr)
knitr::opts_chunk$set(cache.lazy = FALSE)
library('ggplot2')
source('prepare_data.R')
```

## Plot mean~variance
```{r}
ggplot(data = STR_calls_locus, 
       aes(x = mu_locuscoverage_log, y = s_locuscoverage_log)) +
  geom_point(aes(colour = n_zeros/total)) #+
#facet_wrap(~repeatunitlen, scales = 'free') +
#geom_abline(intercept = -0.4056, slope = 0.3435, colour = 'grey') +
#geom_abline(intercept = -1.3, slope = 1, colour = 'red') +
#geom_smooth(method = 'lm')
#ggsave('plots/locuscov_mean_var.jpg')
```


```{r}
# lm(s_locuscoverage_log ~ mu_locuscoverage_log, STR_calls_locus)
# 
# 
# 
# ggplot(data = STR_calls_locus, 
#        aes(x = mu_locuscoverage_log, y = s_locuscoverage_log)) +
#   geom_point(aes(colour = known_pathogenic), alpha = .1) 
# 
# ggplot(data = STR_calls_locus, 
#        aes(x = mu_locuscoverage_log, y = s_locuscoverage_log)) +
#   geom_point(aes(colour = disease_gene), alpha = .3) 
# 
# ggplot(data = subset(STR_calls_locus, signif_0_01 > 0 | (n_zeros/total < 0.90 & mu_locuscoverage_log > 2)), 
#        aes(x = mu_locuscoverage_log, y = s_locuscoverage_log)) +
#   geom_point(aes(colour = signif_0_01))
# 
# ggplot(data = subset(STR_calls_locus, n_zeros/total < 0.90 & mu_locuscoverage_log > 2.2), 
#        aes(x = mu_locuscoverage_log, y = s_locuscoverage_log)) +
#   geom_point(aes(colour = signif_0_01))
# 
# # Plot pLI
# 
# ggplot(data = STR_calls_locus, 
#        aes(x = pLI, colour = in_omim)) +
#   geom_density() +
#   geom_vline(xintercept = 0.9, colour = 'blue')
# 
# ggplot(data = STR_calls_locus, 
#        aes(x = pLI, colour = disease_gene)) +
#   geom_density() +
#   geom_vline(xintercept = 0.9, colour = 'blue')
# 
# 
# ggplot(data = STR_calls_locus, 
#        aes(x = pLI, y = signif_0_01, colour = disease_gene)) +
#   geom_point() +
#   geom_vline(xintercept = 0.9, colour = 'blue')
# #ggsave('plots/pLI_signif')
# 
# ggplot(data = STR_calls_locus, 
#        aes(x = pLI, y = signif_0_01, colour = in_omim)) +
#   geom_point() +
#   geom_vline(xintercept = 0.9, colour = 'blue')
# 
# 
# 
# # Plot observed/expected lof
# 
# ggplot(data = STR_calls_locus, 
#        aes(x = oe_lof, colour = in_omim)) +
#   geom_density() +
#   geom_vline(xintercept = 0.35, colour = 'blue')
# 
# ggplot(data = STR_calls_locus, 
#        aes(x = oe_lof, colour = disease_gene)) +
#   geom_density() +
#   geom_vline(xintercept = 0.35, colour = 'blue')
# 
# ggplot(data = subset(STR_calls_locus, n_zeros/total < 0.90 & mu_locuscoverage_log > 1.5), #STR_calls_locus, 
#        aes(x = oe_lof, y = signif_0_01, colour = disease_gene)) +
#   geom_point() +
#   xlim(NA, 2) +
#   geom_vline(xintercept = 0.35, colour = 'blue')
# ggsave('plots/oeLOF_signif')
# 
# ggplot(data = STR_calls_locus, 
#        aes(x = oe_lof, y = s_locuscoverage_log, colour = in_omim)) +
#   geom_point() +
#   xlim(NA, 2.5) +
#   geom_vline(xintercept = 0.35, colour = 'blue')
# 
# ggplot(data = STR_calls_locus, 
#        aes(x = oe_lof, y = s_locuscoverage_log, colour = disease)) +
#   geom_point() +
#   xlim(NA, 2.5) +
#   geom_vline(xintercept = 0.35, colour = 'blue')
# 
# # Plot feature
# 
# ggplot(data = STR_calls_locus, aes(x = feature, y = signif_0_01)) + 
#   geom_jitter() +
#   geom_violin(colour = 'red') +
#   facet_wrap(~repeatunitlen)
# ggsave('plots/feature_signif_all.jpg')
# 
# ggplot(data = STR_calls_locus, aes(x = feature, y = n_zeros)) + 
#   geom_jitter() +
#   geom_violin(colour = 'red') +
#   facet_wrap(~repeatunitlen)
# ggsave('plots/feature_nzeros_all.jpg')
# 
# ggplot(data = STR_calls_locus, aes(x = feature, y = s_locuscoverage_log)) + 
#   geom_jitter() +
#   geom_violin(colour = 'red') +
#   facet_wrap(~repeatunitlen)
# ggsave('plots/feature_slocuscov_all.jpg')
# 
# ggplot(data = STR_calls_locus, aes(x = feature, y = mu_locuscoverage_log)) + 
#   geom_jitter() +
#   geom_violin(colour = 'red') +
#   facet_wrap(~repeatunitlen)
# ggsave('plots/feature_mulocuscov_all.jpg')
# 
# # Plot TSS
# 
# min_tss = min(STR_subset$closest_TSS_distance, na.rm = T)
# 
# 
# ggplot(data = STR_calls_locus, 
#        aes(x = closest_TSS_distance, y = signif_0_01)) + 
#   geom_vline(xintercept = 0, colour = 'blue') +
#   geom_point()
# ggsave('plots/tss_signif_all.jpg')
# 
# ggplot(data = STR_calls_locus, 
#        aes(x = closest_TSS_distance, y = signif_0_01)) + 
#   geom_vline(xintercept = 0, colour = 'blue') +
#   geom_point() +
#   xlim(min_tss, abs(min_tss))
# ggsave('plots/tss_signif_all_zoom.jpg')
# 
# ggplot(data = STR_calls_locus, 
#        aes(x = closest_TSS_distance, y = signif_0_01)) + 
#   geom_vline(xintercept = 0, colour = 'blue') +
#   geom_point() + 
#   facet_wrap(~repeatunitlen) +
#   xlim(min_tss, abs(min_tss))
# ggsave('plots/tss_signif_all_zoom_facet.jpg')
# 
# 
# 
# # Plot pathogenic
# 
# ggplot(data = subset(STR_calls_locus, !is.na(pathogenic)), 
#        aes(y = signif_0_01, x = feature, label=pathogenic, colour=factor(repeatunitlen))) + 
#   geom_point(size = 2) +
#   geom_text_repel() +
#   labs(subtitle = 'N=219 samples',
#        y = 'number of significant calls per locus at p<0.01')
# ggsave('plots/pathogenic_signif.jpg')
# 
# ggplot(data = subset(STR_calls_locus, !is.na(pathogenic)), 
#        aes(y = s_locuscoverage_log, x = feature, label=pathogenic, colour=factor(repeatunitlen))) + 
#   geom_point(size = 2) +
#   geom_text_repel() +
#   labs(subtitle = 'N=219 samples')
# ggsave('plots/pathogenic_s.jpg')
# 
# 
# ggplot(data = STR_calls_locus, 
#        aes(y = s_locuscoverage_log, x = known_pathogenic)) + 
#   geom_violin() +
#   labs(subtitle = 'N=219 samples')
# ggsave('plots/pathogenic_s_violin.jpg')
# 
# 
# 
# 
# 
# 
# ggplot(data = STR_calls_locus, aes(y = signif_0_01, x = pathogenic)) + 
#   geom_boxplot() +
#   labs(subtitle = 'N=219 samples',
#        x = "overlaps known pathogenic STR locus", 
#        y = 'number of significant calls per locus at p<0.01')
# 
# ggplot(data = subset(STR_calls_locus, !is.na(pathogenic)), aes(y = signif_0_01, x = feature, label=pathogenic)) + 
#   geom_point() +
#   geom_text_repel() +
#   labs(subtitle = 'N=219 samples',
#        y = 'number of significant calls per locus at p<0.01')
# 
# 
# 
# ggplot(data = STR_calls_locus, aes(y = signif_0_01, x = closest_TSS_distance,
#                                    group = closest_TSS_distance)) + 
#   geom_boxplot() +
#   labs(subtitle = 'N=219 samples', 
#        x = "distance to closest TSS", 
#        y = 'number of significant calls per locus at p<0.01')
# 
# 
# 
# ### Plots
# # ggplot(data = RGP_subset, aes(x = closest_TSS_distance)) + 
# #   geom_density() +
# #   xlim(-100000, 100000)
# # 
# # ggplot(data = RGP_subset, aes(y = outlier, x = closest_TSS_distance)) + 
# #   geom_boxplot(aes(group = cut_width(closest_TSS_distance, 20000))) +
# #   xlim(-100000, 100000)
# # 
# # ggplot(data = subset(RGP_subset, outlier > 1), aes(y = outlier, x = closest_TSS_distance)) + 
# #   geom_point() +
# #   xlim(-100000, 100000)
# # 
# # ggplot(data = RGP_subset, aes(y = outlier, x = abs(closest_TSS_distance))) + 
# #   geom_point() +
# #   xlim(0, 700000)
# # 
# # 
# # ggplot(data = RGP_subset, aes(y = outlier, x = feature)) + 
# #   geom_boxplot() 
# 
# ggplot(data = STR_calls_locus, aes(x = signif_0_01, fill = feature)) +
#   geom_bar() 
# 
# #zoom in
# ggplot(data = subset(STR_calls_locus, signif_0_01 > 10), aes(x = signif_0_01, fill = feature)) +
#   geom_bar() 
# 
# 
# #subset(STR_calls_locus, signif_0_01 > 0 & feature == 'CDS')[,c(2,3,4,5,10,11,13,17,18,19)]
# 
# ggplot(data = STR_calls_locus, aes(x = signif_0_01)) +
#   facet_wrap(~feature) +
#   geom_bar() 
# 
# ggplot(data = subset(STR_calls_locus, feature = 'CDS'), aes(x = signif_0_01)) +
#   geom_bar() 
```